#!/usr/bin/env python3
"""Markdown renderer for the executive state surface (SDD-002 `state.md`).

Extracted from `state_builder.py` under SDD-048 (C-1 god-module split; C-2
right-sizing the stdlib-only render rule). The former monolithic
`render_markdown` f-string wall is decomposed here into one helper per SDD-002
section, using stdlib `string.Template` for the static header and fleet
scaffolds. No behaviour change: `state.md` output is byte-equivalent to the
pre-split renderer (SDD-048 C-1 R-7 / C-2 R-2).

Style: pure Python stdlib (LESSON-001 / ADR-023). No third-party dependencies.
"""

from __future__ import annotations

import sys
from pathlib import Path
from string import Template

# In-tree sibling bootstrap (ADR-012): make sibling modules importable by bare
# name regardless of the caller's sys.path.
CLI_DIR = Path(__file__).resolve().parent
if str(CLI_DIR) not in sys.path:
    sys.path.insert(0, str(CLI_DIR))

from state_builder_data import (  # noqa: E402  -- in-tree sibling re-export (ADR-012)
    BacklogItem,
    Feature,
    LedgerView,
    PIBlock,
)
from schema_lint import UserGate  # noqa: E402  -- shared contract (ADR-012)
from state_builder_html import active_user_gates  # noqa: E402  -- in-tree sibling (ADR-012)


# ---------------------------------------------------------------------------- #
# Static section scaffolds (stdlib string.Template; SDD-048 C-2 R-2)
#
# string.Template gives a dependency-free, injection-safe interpolation for the
# fixed-shape header and fleet blocks. Substituted values are inserted literally
# (Template does not re-scan them), so a stray "$" in a value is harmless.
# ---------------------------------------------------------------------------- #

_HEADER_TMPL = Template(
    "# Executive State\n"
    "\n"
    "Generated date: $generated_date\n"
    "Current PI: $pi_label\n"
    "Active sprint: $sprint_label\n"
    "Active focus: $focus_line"
)

_FLEET_TMPL = Template(
    "## Fleet\n"
    "\n"
    "- Principals: $principals\n"
    "- Generic workers: $generic\n"
    "- Specialists: $specialist\n"
    "- Total agents: $total_agents\n"
    "- Skills: $total_skills across $skill_categories categories"
)

_SPRINT_LABEL = "Symbolic -- AI fleet compresses wall-clock time"

_FOOTER_LINES = [
    "",
    "---",
    "",
    "_Auto-generated by `cli/state_builder.py`. SDD-002 contract: 7-section format. "
    "Visual dashboard: `python state_builder.py serve`._",
    "",
]


# ---------------------------------------------------------------------------- #
# Per-section helpers (one per SDD-002 section; each well under ~120 lines)
# ---------------------------------------------------------------------------- #

def _md_header(*, generated_date: str, pi: PIBlock | None,
               next_action: tuple[str, str, str | None]) -> list[str]:
    """Section 1: header block plus the optional PI-progress line."""
    pi_label = f"{pi.name} ({pi.title})" if pi else "no PI active"
    focus_line = next_action[0] if next_action else ""
    out = _HEADER_TMPL.substitute(
        generated_date=generated_date,
        pi_label=pi_label,
        sprint_label=_SPRINT_LABEL,
        focus_line=focus_line,
    ).split("\n")
    out.append("")
    if pi:
        out += [f"PI progress: {pi.done}/{pi.total} commitments complete ({pi.pct}%)", ""]
    return out


def _md_spec_pipeline(features: list[Feature]) -> list[str]:
    """Section 2: spec-pipeline table (one row per feature)."""
    out = ["## Spec Pipeline", "",
           "| Feature | Stage | Status | Notes |",
           "|---------|-------|--------|-------|"]
    if features:
        for f in features:
            out.append(f"| {f.name} | {f.stage} | {f.status_line or '-'} | {f.notes} |")
    else:
        out.append("| _(no features)_ | -- | -- | -- |")
    out.append("")
    return out


def _md_sprint_plan(backlog: list[BacklogItem]) -> list[str]:
    """Section 3: sprint plan grouped by sprint (scheduled sprints only)."""
    out = ["## Sprint Plan", ""]
    if backlog:
        by_sprint: dict[str, list[BacklogItem]] = {}
        for item in backlog:
            key = item.sprint or "Unassigned"
            by_sprint.setdefault(key, []).append(item)
        for sprint_key in sorted(by_sprint.keys()):
            if sprint_key.lower() in ("unscheduled", "unassigned"):
                continue
            out.append(f"### {sprint_key}")
            out.append("")
            out.append("| ID | Title | Priority | RICE | Status |")
            out.append("|----|-------|----------|------|--------|")
            for it in by_sprint[sprint_key]:
                out.append(f"| {it.pid} | {it.title} | {it.priority} | {it.rice} | {it.status} |")
            out.append("")
    else:
        out += ["_no items_", ""]
    return out


def _md_fleet(roster: dict) -> list[str]:
    """Section 4: fleet roster counts."""
    out = _FLEET_TMPL.substitute(
        principals=roster["principals"],
        generic=roster["generic"],
        specialist=roster["specialist"],
        total_agents=roster["total_agents"],
        total_skills=roster["total_skills"],
        skill_categories=roster.get("skill_categories", 0),
    ).split("\n")
    out.append("")
    return out


def _md_recently_completed(ledger: LedgerView) -> list[str]:
    """Section 5: recent successful dispatches from the fleet ledger."""
    out = ["## Recently Completed", ""]
    if not ledger.available:
        out += ["_fleet.db not initialized; no ledger data to summarize_", ""]
    elif not ledger.recent_success:
        out += ["_no successful dispatches yet_", ""]
    else:
        out += ["| When | Feature | Task | Agent |",
                "|------|---------|------|-------|"]
        for d in ledger.recent_success:
            when = d.get("outcome_at") or d.get("dispatched_at") or ""
            out.append(f"| {when} | {d.get('feature_dir','')} | {d.get('task_title','')} | {d.get('agent_id','')} |")
        out.append("")
    return out


def _md_blockers(ledger: LedgerView, user_gates: list[UserGate] | None) -> list[str]:
    """Section 6: pending user gates plus stale-dispatch blockers."""
    out = ["## Blockers", ""]
    blocking_gates = active_user_gates(user_gates or [])
    if blocking_gates:
        out += [
            "### Pending User Gates",
            "",
            "| Feature | Gate | Blocks | Evidence Need | Next Action |",
            "|---------|------|--------|---------------|-------------|",
        ]
        for gate in blocking_gates:
            out.append(
                f"| {gate.feature} | {gate.gate_id} (`{gate.gate_type}`) | "
                f"`{gate.blocking_scope}` | {gate.evidence_type or '-'} | "
                f"{gate.next_action or '-'} |"
            )
        out += [
            "",
            "_Generated executive surfaces are visibility only; they are not approval evidence._",
            "",
        ]
    if not ledger.available:
        out += ["_fleet.db not initialized; no blockers known_", ""]
    elif not ledger.blockers:
        out += ["_none -- no dispatches without outcome older than 24h_", ""]
    else:
        out += ["| Dispatched | Feature | Task | Agent | Age |",
                "|-----------|---------|------|-------|-----|"]
        for d in ledger.blockers:
            out.append(f"| {d.get('dispatched_at','')} | {d.get('feature_dir','')} | "
                       f"{d.get('task_title','')} | {d.get('agent_id','')} | stale |")
        out.append("")
    return out


def _md_next_milestones(pi: PIBlock | None) -> list[str]:
    """Section 7: next milestones from the active PI's unchecked commitments."""
    out = ["## Next Milestones", ""]
    if pi and pi.checkboxes:
        unstarted = [label for done, label in pi.checkboxes if not done]
        if unstarted:
            for label in unstarted[:5]:
                out.append(f"- {label}")
        else:
            out.append("_all PI commitments complete -- plan next PI_")
    else:
        out.append("_no PI commitments registered_")
    return out


def _md_footer() -> list[str]:
    """Trailing auto-generated provenance footer (SDD-002 contract)."""
    return list(_FOOTER_LINES)


# ---------------------------------------------------------------------------- #
# Orchestrator
# ---------------------------------------------------------------------------- #

def render_markdown(*, generated_date: str, pi: PIBlock | None, features: list[Feature],
                    backlog: list[BacklogItem], roster: dict, ledger: LedgerView,
                    next_action: tuple[str, str, str | None],
                    user_gates: list[UserGate] | None = None) -> str:
    """Produce state.md in the canonical 7-section format required by SDD-002.

    Sections (in order):
      1. Header
      2. Spec Pipeline
      3. Sprint Plan
      4. Fleet
      5. Recently Completed
      6. Blockers
      7. Next Milestones

    Decomposed under SDD-048 into per-section helpers; output is byte-equivalent
    to the pre-split monolithic renderer.
    """
    out: list[str] = []
    out += _md_header(generated_date=generated_date, pi=pi, next_action=next_action)
    out += _md_spec_pipeline(features)
    out += _md_sprint_plan(backlog)
    out += _md_fleet(roster)
    out += _md_recently_completed(ledger)
    out += _md_blockers(ledger, user_gates)
    out += _md_next_milestones(pi)
    out += _md_footer()
    return "\n".join(out)
